### ISSUE TITLE
Microsoft is Removing all Apps without IARC age rating off the store! It's a one click process in the Dev Center and only takes a minute!

### ISSUE THREAD

**Issue by ghost** [Khan/khan-windows#120]
![16_capture_story](https://cloud.githubusercontent.com/assets/7173984/16172671/fbebd3c2-355a-11e6-9f8b-0a408f0ec1e4.jpg)
Please do this soon! I know you aren't actively supporting the platform, but people still use the app!

**Comment by CoryKhan** [comment]
Hello Roger,

Thank you for reporting this to us.  We will update the age ratings soon!

**Comment by ghost** [comment]
I still haven't seen an ESRB rating on it's listing yet! Have you set it up yet or has MS reversed its stance?

**Comment by CoryKhan** [comment]
Hello Roger,

We are unable to update the age rating until 7/21/2016 due to security reasons.

**Comment by ghost** [comment]
@CoryKhan It is now 7/27. Is it possible now?
